const quotes = [
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins."
];

window.quotes = quotes;