const quotes = [
  "Small improvements create remarkable results.",
  "Consistency beats intensity over time.",
  "Progress grows from daily action.",
  "Quality is built one decision at a time.",
  "Focus on the next useful step.",
  "Learning compounds every day.",
  "Reliable habits create reliable outcomes.",
  "Every challenge teaches something valuable.",
  "Persistence turns effort into achievement.",
  "Success is a collection of small wins.",
  "Done is better than perfect.",
  "Stay curious and keep learning.",
  "Every expert was once a beginner.",
  "Discipline creates freedom.",
  "Simple solutions are often the strongest.",
  "Progress is progress, no matter how small.",
  "Focus creates momentum.",
  "Customer trust is earned through quality.",
  "Think like a user.",
  "Great products come from continuous improvement.",
  "Every bug discovered is an opportunity to improve.",
  "Automation amplifies good processes.",
  "Quality starts with attention to detail.",
  "Learning never exhausts the mind.",
  "Keep improving the process.",
  "Small habits create big changes.",
  "Stay patient with your growth.",
  "Consistency compounds over time.",
  "Automation saves time for innovation.",
  "Find the root cause, not the symptom.",
  "Success is preparation meeting opportunity.",
  "Take ownership of the outcome.",
  "Curiosity drives innovation.",
  "Make each day count.",
  "Don't fear failure, fear standing still.",
  "Focus on solutions, not obstacles.",
  "Growth begins outside your comfort zone.",
  "Write code for people first, computers second.",
  "A good test today prevents a problem tomorrow.",
  "Every challenge is a chance to improve.",
  "Build with purpose.",
  "Keep your standards high.",
  "Quality is everyone's responsibility.",
  "Be consistent, not occasional.",
  "Learning is a lifelong advantage.",
  "Progress comes from persistence.",
  "Stay adaptable in a changing world.",
  "Excellence is a habit, not an event.",
  "The best investment is in yourself.",
  "Never stop improving.",
  "Every test tells a story.",
  "Think before you automate.",
  "Good systems reduce mistakes.",
  "Strong habits outperform motivation.",
  "Preparation reduces uncertainty.",
  "Details determine quality.",
  "A clear mind creates better solutions.",
  "Feedback is a gift.",
  "Trust is built through reliability.",
  "Stay hungry for knowledge.",
  "A solved problem creates new opportunities.",
  "Quality matters when nobody is watching.",
  "Keep things simple.",
  "Data beats assumptions.",
  "Measure what matters.",
  "Ask better questions.",
  "Learning starts with curiosity.",
  "Quality is a daily choice.",
  "Focus beats multitasking.",
  "Clarity drives productivity.",
  "Process creates consistency.",
  "Growth requires discomfort.",
  "Keep testing your assumptions.",
  "Momentum is built through action.",
  "Improvement begins with awareness.",
  "Success follows preparation.",
  "Patience strengthens progress.",
  "Small steps build great journeys.",
  "Stay focused on the objective.",
  "Innovation starts with curiosity.",
  "Learning creates opportunities.",
  "Persistence unlocks results.",
  "Good design solves problems.",
  "Care about the details.",
  "Build trust through quality.",
  "Be proud of your work.",
  "Stay resilient during setbacks.",
  "Quality reduces rework.",
  "Solve problems at the source.",
  "Make every effort count.",
  "Stay open to feedback.",
  "Use failures as lessons.",
  "Continuous improvement wins.",
  "Strong foundations support growth.",
  "Test what matters most.",
  "Keep your promises.",
  "Build systems that scale.",
  "Think long term.",
  "Progress rewards consistency.",
  "Keep learning new skills.",
  "Success is a daily practice.",
  "Work with intention.",
  "Good habits beat good intentions.",
  "Improvement creates confidence.",
  "Clarity beats complexity.",
  "Always be learning.",
  "Stay committed to excellence.",
  "Great outcomes require effort.",
  "Focus on value.",
  "Quality builds reputation.",
  "Be curious about everything.",
  "Plan, execute, improve.",
  "Strong teams build strong products.",
  "Quality begins with mindset.",
  "Learn from every experience.",
  "Think clearly, act decisively.",
  "Better questions lead to better answers.",
  "Consistency creates trust.",
  "Aim for progress, not perfection.",
  "Do the important work first.",
  "Simple processes are easier to improve.",
  "Progress follows persistence.",
  "Knowledge grows when shared.",
  "Ownership drives results.",
  "Stay focused on the user.",
  "Success starts with responsibility.",
  "Build solutions, not excuses.",
  "Care deeply about quality.",
  "Listen before deciding.",
  "Keep improving your craft.",
  "Every detail contributes.",
  "Master the fundamentals.",
  "Focus on meaningful work.",
  "Stay adaptable and resilient.",
  "Every problem hides a lesson.",
  "Progress begins with action.",
  "Build confidence through practice.",
  "Successful people keep learning.",
  "Stay calm under pressure.",
  "Quality protects trust.",
  "Think critically.",
  "Curiosity fuels growth.",
  "Persistence creates momentum.",
  "Keep moving forward.",
  "Strong effort delivers results.",
  "Choose growth every day.",
  "Keep your standards consistent.",
  "Small wins build confidence.",
  "Practice creates mastery.",
  "Good testing prevents surprises.",
  "Keep improving one step at a time.",
  "Success favors preparation.",
  "Stay disciplined.",
  "Good decisions require good information.",
  "Measure progress regularly.",
  "Learn from mistakes quickly.",
  "Focus on what matters.",
  "Stay committed to quality.",
  "Continuous learning pays dividends.",
  "Build better habits.",
  "Improve the process, improve the outcome.",
  "Growth comes from persistence.",
  "Simple is sustainable.",
  "Trust the process.",
  "Stay curious about improvement.",
  "Make quality visible.",
  "Always seek understanding.",
  "Strong habits create strong results.",
  "Excellence requires consistency.",
  "Invest in learning.",
  "Every day is a chance to improve.",
  "Success grows from discipline.",
  "Stay focused, stay steady.",
  "Better systems create better outcomes.",
  "Test aggressively, learn continuously.",
  "Act with purpose.",
  "Progress requires patience.",
  "Keep solving meaningful problems.",
  "Learn, adapt, improve.",
  "Strong preparation creates confidence.",
  "Pay attention to details.",
  "Reliable work builds trust.",
  "Every improvement matters.",
  "Keep your goals clear.",
  "Think about the user experience.",
  "Good habits reduce friction.",
  "Quality is never accidental.",
  "Growth takes time.",
  "Action beats hesitation.",
  "Stay positive and productive.",
  "Improve something every day.",
  "Focus on root causes.",
  "Work smart and consistently.",
  "Learn faster through practice.",
  "Quality is a competitive advantage.",
  "Stay accountable.",
  "Build momentum daily.",
  "Make learning a habit.",
  "Keep your focus sharp.",
  "Improvement is endless.",
  "Patience and persistence win.",
  "Take the next right step.",
  "Success grows gradually.",
  "Stay committed to the journey.",
  "Every day offers a lesson.",
  "Build confidence through repetition.",
  "Refine continuously.",
  "Good work speaks for itself.",
  "Keep challenging yourself.",
  "Learning creates possibilities.",
  "Act consistently.",
  "Stay reliable.",
  "Keep the user in mind.",
  "Quality creates lasting value.",
  "Strong processes reduce risk.",
  "Think ahead.",
  "Learn from success and failure.",
  "Progress rewards discipline.",
  "Build for the future.",
  "Stay organized and focused.",
  "A growth mindset changes everything.",
  "Make decisions with purpose.",
  "Value continuous improvement.",
  "Practice deliberate learning.",
  "Don't stop at good enough.",
  "Excellence follows effort.",
  "Stay committed to growth.",
  "Focus on impact.",
  "Reliable systems create confidence.",
  "Learn deeply, not quickly.",
  "Great work requires attention.",
  "Keep improving the basics.",
  "Every problem is solvable.",
  "Think systematically.",
  "Action creates opportunity.",
  "Stay persistent through challenges.",
  "Build quality into the process.",
  "Treat feedback as fuel.",
  "Mastery comes from repetition.",
  "Create value every day.",
  "Strong work builds credibility.",
  "Test thoroughly.",
  "Stay dedicated to learning.",
  "Improve before optimizing.",
  "Quality inspires confidence.",
  "Think about long-term value.",
  "Good habits support success.",
  "Keep experimenting.",
  "Every effort teaches something.",
  "Focus on sustainable progress.",
  "Small actions create momentum.",
  "Stay focused on outcomes.",
  "Improve with every iteration.",
  "Build trust one action at a time.",
  "Consistency creates excellence.",
  "Learn continuously and apply wisely.",
  "Quality and speed can coexist.",
  "Be intentional with your efforts.",
  "The journey creates the result.",
  "Stay curious about possibilities.",
  "Grow through challenges.",
  "Every achievement begins with a decision.",
  "Think clearly and execute well.",
  "Keep building your future.",
  "Success starts with showing up.",
  "Stay committed when motivation fades.",
  "Great outcomes start with small actions.",
  "Every improvement begins with awareness.",
  "Keep your attention on what matters.",
  "Patience makes progress sustainable.",
  "Strong character supports lasting success.",
  "Learn something worth sharing.",
  "Quality grows from consistency.",
  "Success rewards persistence.",
  "Every day is a new opportunity to improve.",
  "Think carefully and execute confidently.",
  "Progress is built through repetition.",
  "Good habits are investment vehicles.",
  "Focus on what creates value.",
  "Adaptability is a competitive advantage.",
  "Create systems that support success.",
  "Every lesson has practical value.",
  "Make reliability your reputation.",
  "The best solutions are often simple.",
  "Improve the process before the outcome.",
  "Success follows responsibility.",
  "Keep refining your approach.",
  "Growth is a result of effort.",
  "Stay curious about better ways.",
  "Every challenge improves resilience.",
  "Learning increases possibilities.",
  "Think beyond the obvious.",
  "Keep building useful skills.",
  "Progress requires dedication.",
  "Quality work reflects quality thinking.",
  "Resilience turns obstacles into lessons.",
  "Build confidence through preparation.",
  "Stay focused under pressure.",
  "Great teams thrive on trust.",
  "Learning expands potential.",
  "Success depends on consistency.",
  "Improve one thing every day.",
  "Attention creates accuracy.",
  "Ownership creates accountability.",
  "Strong foundations support innovation.",
  "Stay disciplined through uncertainty.",
  "Every effort compounds over time.",
  "Think in solutions.",
  "Keep your standards intentional.",
  "Good work creates opportunities.",
  "Consistency outlasts motivation.",
  "Continuous learning creates growth.",
  "Every setback carries a lesson.",
  "Build quality from the beginning.",
  "Focus transforms effort into results.",
  "Stay dependable.",
  "Mastery grows through repetition.",
  "Strong preparation reduces risk.",
  "Make progress your priority.",
  "Every detail contributes to excellence.",
  "Stay open to improvement.",
  "Think clearly before acting.",
  "Growth requires patience and effort.",
  "Quality earns confidence.",
  "Care about craftsmanship.",
  "Build for long-term success.",
  "Every day offers new insight.",
  "Stay organized and intentional.",
  "Reliable habits create reliable results.",
  "Success is a practice, not an event.",
  "Understand first, improve second.",
  "Progress rewards commitment.",
  "Keep moving despite obstacles.",
  "Stay accountable for outcomes.",
  "Clarity improves execution.",
  "Learning strengthens confidence.",
  "Invest energy where it matters most.",
  "Keep improving the fundamentals.",
  "Quality always leaves a trace.",
  "Persistence beats resistance.",
  "Good judgment comes from experience.",
  "Create value before seeking recognition.",
  "Focus is a force multiplier.",
  "Build trust through actions.",
  "Every improvement starts with a decision.",
  "Stay calm and think critically.",
  "Keep your vision clear.",
  "Success grows from discipline.",
  "Adapt and continue forward.",
  "Learning unlocks new perspectives.",
  "The next step is the most important one.",
  "Progress begins with action today.",
  "Strong effort creates strong results.",
  "Stay committed to excellence.",
  "Quality is a reflection of care.",
  "Create momentum through consistency.",
  "Every challenge develops strength.",
  "Keep learning from every outcome.",
  "Results follow focused effort.",
  "Be intentional with your time.",
  "Think big, execute small.",
  "Every accomplishment starts with a first step.",
  "Stay persistent and keep improving.",
  "Good habits shape great futures.",
  "Success belongs to those who continue.",
  "Build quality before building features.",
  "A careful review prevents costly mistakes.",
  "The smallest improvement is still improvement.",
  "Excellence begins with attention.",
  "Stay focused on creating value.",
  "Every improvement strengthens the foundation.",
  "Great results come from steady effort.",
  "Success follows disciplined execution.",
  "Learn faster than the problems change.",
  "Quality creates confidence.",
  "Do fewer things, but do them well.",
  "Every day is a chance to improve your craft.",
  "Strong habits outperform strong intentions.",
  "The best time to improve is now.",
  "Build solutions that last.",
  "Understanding comes before improvement.",
  "Keep your work simple and maintainable.",
  "A thoughtful process prevents avoidable problems.",
  "Reliable systems start with reliable people.",
  "Consistency creates credibility.",
  "Growth happens one lesson at a time.",
  "Pay attention to the details others ignore.",
  "Improvement starts with honest feedback.",
  "Strong foundations support innovation.",
  "Take pride in what you create.",
  "Every challenge develops capability.",
  "Quality reduces future effort.",
  "Stay curious about better ways of working.",
  "Knowledge grows when applied.",
  "Focus on progress, not applause.",
  "Keep your standards higher than your excuses.",
  "Simple solutions deserve respect.",
  "Success begins with showing up.",
  "Every bug fixed improves someone's experience.",
  "The best improvements are often small.",
  "Learn from every release.",
  "Strong teams learn continuously.",
  "Progress comes from persistence, not perfection.",
  "Build trust through consistency.",
  "Create systems that help people succeed.",
  "Think beyond the immediate problem.",
  "Every effort contributes to mastery.",
  "Great work is built on fundamentals.",
  "Stay patient with long-term goals.",
  "Reliable habits create reliable performance.",
  "Preparation creates opportunities.",
  "Invest in skills that compound.",
  "Learn deeply and apply broadly.",
  "Small actions shape the future.",
  "Quality is visible in the details.",
  "Great products come from continuous refinement.",
  "Keep improving even when nobody notices.",
  "Focus is a superpower.",
  "Every lesson adds value.",
  "Be deliberate with your decisions.",
  "Progress thrives on momentum.",
  "Strong work requires strong discipline.",
  "Clarity eliminates unnecessary complexity.",
  "Learning is fuel for innovation.",
  "Consistency creates lasting results.",
  "Keep solving the right problems.",
  "Reliable execution builds trust.",
  "Success grows through repetition.",
  "A clear process supports quality.",
  "Challenge assumptions respectfully.",
  "Stay committed to learning.",
  "Craftsmanship is attention made visible.",
  "Quality is remembered long after speed is forgotten.",
  "Good work deserves careful effort.",
  "Keep asking better questions.",
  "Think carefully, implement confidently.",
  "Success is rarely accidental.",
  "Improvement is a daily activity.",
  "Learn something useful every day.",
  "Details are where quality lives.",
  "Effective work starts with focus.",
  "Quality starts before testing begins.",
  "Strong preparation strengthens execution.",
  "Continuous improvement never goes out of style.",
  "Resilience grows through challenge.",
  "Keep building valuable habits.",
  "Make learning part of your identity.",
  "The next improvement is always possible.",
  "Better systems create better outcomes.",
  "Consistency beats occasional brilliance.",
  "Strong processes free creativity.",
  "Stay curious when things get difficult.",
  "Good results require patience.",
  "Every effort teaches something.",
  "Keep refining your approach.",
  "Success is earned before it is visible.",
  "Growth comes from repeated practice.",
  "Build confidence through competence.",
  "Reliable work earns respect.",
  "Think about tomorrow while working today.",
  "Master the basics repeatedly.",
  "Keep improving the experience.",
  "Small disciplines create major advantages.",
  "Trust is built one action at a time.",
  "Focus on what can be improved.",
  "Every achievement begins with commitment."
];

window.quotes = quotes;